<Project>
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>David Eriksson</Authors>
    <Copyright>Copyright (c) 2026 David Eriksson</Copyright>
    <RepositoryUrl>https://github.com/activout/Activout.C9.Scheduler</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
